function [fval, exitflag, output, x] = runfleq1
% RUNFLEQ1 demonstrates 'HessMult' option for FMINCON with linear
% equalities.
% Documentation example.

%   Copyright 1984-2015 The MathWorks, Inc.

problem = load('fleq1');   % Get V, Aeq, beq
V = problem.V; Aeq = problem.Aeq; beq = problem.beq;
n = 1000;             % problem dimension
xstart = -ones(n,1); xstart(2:2:n,1) = ones(length(2:2:n),1); % starting point
options = optimoptions(@fmincon, ...
    'Algorithm', 'trust-region-reflective',  ...
    'SpecifyObjectiveGradient', true, ...
    'HessianMultiplyFcn', @(Hinfo,Y)hmfleq1(Hinfo,Y,V), ...
    'Display', 'iter', ...
    'OptimalityTolerance', 1e-9, ...
    'FunctionTolerance', 1e-9); 
[x,fval,exitflag,output] = fmincon(@(x)brownvv(x,V),xstart,[],[],Aeq,beq,[],[], ...
                                    [],options);
